spring:
  config:
    activate:
      on-profile: local

  redis:
    host: localhost
    port: 6379

---
spring:
  config:
    activate:
      on-profile: dev

  redis:
    host: ${REDIS_HOST_DEV}
    port: ${REDIS_HOST_PORT}